window.GameState = {
    isHost: false, 
    myId: null, 
    roomId: null, 
    isInGame: false, 
    isClickedIn: false, 
    testingMode: false,
    peers: {}, 
    localPos: { x: window.innerWidth/2, y: window.innerHeight/2 },
    lastSentMouse: { x: 0, y: 0 }, 
    localCursorEl: null, 
    localShape: window.Assets.PATH_POINTER,
    baseZ: {}, 
    currentZMap: {}, 
    overlaps: {}, 
    activeDrags: {}, 
    slapCombos: {}, 
    hfCombos: {},
    interactingPeer: null, 
    isDragging: false, 
    isEmptyClick: false,
    dragStartPos: { x: 0, y: 0 }, 
    mouseDownTime: 0, 
    recentHits: {}, 
    pendingHitTimeout: null
};